spring:
  application:
    name: ib-demo
  profiles:    active:    - dev

ib:
  core:    speed: 1.0
    image-update-frame: 3
  repo:    remote-url: http://localhost:80
  mode:
    story:
      enable: true
      stages:
      - cn.milai.ibdemo.dramafile.Hello
