spring:
  application:
    name: ib-demo-endless
  profiles:    active:    - dev

#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - "*"
#  server:
#    port: 8080

ib:
  core:    speed: 1.0
    image-update-frame: 3
  repo:    remote-url: http://localhost:80